### ISSUE TITLE
RuntimeException: Could not execute entrypoint stage 'main' due to errors

### ISSUE THREAD

**Issue by DakksNessik** [NinjaPhenix/FabricMods#56]
I am having issues with getting our 1.16.2 server to start with the Expanded storage, version 5.4.18, mod installed. I have even created a standalone server with only the mod installed with the same effect. I will post the details below, please let me know if I can provide any additional information and thank you in advance for your assistance.

Java Version: OpenJDK Corretto-8.265.01.1 64bit
Java Options: Tried with and without options.
<code>-Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M</code>
Minecraft Jar Version: 1.16.2
Fabric installer Version: 0.6.1.45
Mods: 
  Fabric-api-0.18.0+397-1.16
  ExpandedStorage-5.4.18+1.16.2

<details>
  <summary>latest.log</summary>
<p>
<code>
[16:44:59] [main/INFO]: Loading for game Minecraft 1.16.2
[16:44:59] [main/INFO]: [FabricLoader] Loading 43 mods: fabric-screen-handler-api-v1@1.1.0+872498414e, minecraft@1.16.2, fabric-renderer-api-v1@0.2.13+eae12eb84e, fabric-networking-blockentity-v0@0.2.5+b50ffc7b4e, fabric-keybindings-v0@0.2.0+3fa9f7c54e, jankson@3.0.0+j1.2.0, fabric-command-api-v1@1.0.8+5ce533984e, fabricloader@0.9.1+build.205, fabric-tool-attribute-api-v1@1.2.1+02fb8fda4e, fabric-renderer-indigo@0.3.4+5d32f5834e, fabric-containers-v0@0.1.8+045df74f4e, fabric-object-builder-api-v1@1.6.0+e81ec80b4e, fabric-item-api-v1@1.0.0+16acbe5b4e, fabric-events-interaction-v0@0.3.3+7066030f4e, fabric-crash-report-info-v1@0.1.2+b7f9825d4e, fabric-game-rule-api-v1@1.0.1+91555cd14e, fabric-api-base@0.1.3+12a8474c4e, fabric-rendering-v0@1.1.0+534104904e, fabric-rendering-v1@1.2.0+fc24ff244e, fabric-key-binding-api-v1@1.0.1+730711c64e, fabric-rendering-data-attachment-v1@0.1.3+b7f9825d4e, fabric-resource-loader-v0@0.2.9+e5d3217f4e, chainmail@0.4.1, fabric-textures-v0@1.0.4+eae12eb84e, expandedstorage@5.4.18, fabric-content-registries-v0@0.1.9+059ea8664e, fabric-tag-extensions-v0@1.0.3+ac8e8c594e, ninjaphenix-container-lib@1.1.6, fabric-rendering-fluids-v1@0.1.10+e5d3217f4e, fabric-registry-sync-v0@0.4.3+e5d3217f4e, fabric-commands-v0@0.2.0+52d308364e, fabric-blockrenderlayer-v1@1.1.4+c6a8ea894e, fabric-lifecycle-events-v1@1.2.0+74cc3b204e, fabric-mining-levels-v0@0.1.2+b764ce994e, fabric-renderer-registries-v1@2.1.0+e2862de64e, fabric-loot-tables-v1@1.0.0+fac8f3664e, fabric-events-lifecycle-v0@0.2.0+16acbe5b4e, fabric@0.18.0+build.397-1.16, fabric-particles-v1@0.2.1+0a6f2a704e, fabric-models-v0@0.1.0+dfdb52d64e, fabric-item-groups-v0@0.2.0+438f96364e, fabric-object-builders-v0@0.6.1+ba4afa574e, fabric-networking-v0@0.1.10+e00ecb5f4e
[16:44:59] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.1 Source=file:/D:/servertest/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[16:45:06] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
[16:45:06] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'expandedstorage'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:32) ~[fabric-server-launch.jar:?]
	at net.minecraft.server.Main.main(Main.java:126) [intermediary-server.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26) [fabric-server-launch.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49) [fabric-server-launch.jar:?]
Caused by: java.lang.NoSuchMethodError: net.minecraft.class_2348.method_10250(Lnet/minecraft/class_2960;)Z
	at ninjaphenix.expandedstorage.content.ModItems.registerConversionPath(ModItems.java:37) ~[expandedstorage-5.4.18+1.16.2.jar:?]
	at ninjaphenix.expandedstorage.content.ModItems.init(ModItems.java:21) ~[expandedstorage-5.4.18+1.16.2.jar:?]
	at ninjaphenix.expandedstorage.ExpandedStorage.onInitialize(ExpandedStorage.java:35) ~[expandedstorage-5.4.18+1.16.2.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
	... 17 more
</code>
</p>
</details>

**Comment by NinjaPhenix** [comment]
Should be fixed in latest version ( 3.4.19+1.16.2) https://www.curseforge.com/minecraft/mc-mods/expanded-storage-fabric/files/3034769
